// Generated by scripts/package.js immediately before packaging — swapped in
// with the real base64-encoded node-v108 better_sqlite3.node binary, then
// restored to this placeholder afterward. Never edit by hand. Empty in dev;
// only read when running inside a pkg-packaged executable (see
// sync/queue.ts's resolveNativeBinding), so an empty placeholder is safe.
export const NATIVE_BINDING_BASE64 = ''
