#!/usr/bin/env node
// Packages the agent into a standalone .exe.
//
// Two separate native-module problems have to be solved, both around
// better-sqlite3:
//
// 1. ABI mismatch — pkg's node18-win-x64 target bundles a Node runtime with
//    NODE_MODULE_VERSION 108. better-sqlite3 in node_modules is compiled
//    against whatever Node runs locally (dev machine ABI, e.g. 137 for
//    Node 24), so the two don't match and the packaged exe crashes on
//    launch. Fix: swap in better-sqlite3's official node-v108 prebuilt
//    binary just for the pkg step, then restore the dev-ABI binary
//    afterward so `npm run dev` keeps working locally.
//
// 2. pkg can't actually load the native binary at runtime even once the ABI
//    matches. pkg's `assets`/`scripts` config (the normally-recommended fix
//    for bundling native addons) turned out unreliable for this project —
//    verified via `pkg --debug` that the .node file was never even
//    attempted for inclusion despite being correctly declared, and the
//    packaged exe crashed with "Could not locate the bindings file" (or,
//    once that was chased down, "was not included into executable at
//    compilation stage") when run from a directory with no adjacent
//    node_modules — the only way to actually catch this, since running it
//    from inside the source tree falsely "works" by resolving against the
//    real adjacent node_modules on disk instead of the packaged asset.
//    Fix: base64-encode the v108 binary directly into a plain .ts source
//    module (src/sync/nativeBinding.generated.ts) that tsc/pkg bundle like
//    any other file — no special asset handling needed — and decode it to
//    a real file next to the exe at runtime (see sync/queue.ts).
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const bsq3Dir = path.join(root, 'node_modules', 'better-sqlite3');
const releaseDir = path.join(bsq3Dir, 'build', 'Release');
const devBinary = path.join(releaseDir, 'better_sqlite3.node');
const devBackup = path.join(releaseDir, 'better_sqlite3.dev.node');
const generatedFile = path.join(root, 'src', 'sync', 'nativeBinding.generated.ts');
const PLACEHOLDER = "// Generated by scripts/package.js immediately before packaging — swapped in\n// with the real base64-encoded node-v108 better_sqlite3.node binary, then\n// restored to this placeholder afterward. Never edit by hand. Empty in dev;\n// only read when running inside a pkg-packaged executable (see\n// sync/queue.ts's resolveNativeBinding), so an empty placeholder is safe.\nexport const NATIVE_BINDING_BASE64 = ''\n";

// pkg's "node18" target's exact ABI (108) is confirmed by the runtime crash message
// itself, not guessed - see NODE_MODULE_VERSION in the error this script fixes.
const PKG_NODE_TARGET = '18.20.4';

function run(cmd, cwd) {
  console.log(`> ${cmd}`);
  execSync(cmd, { stdio: 'inherit', cwd });
}

fs.copyFileSync(devBinary, devBackup);
try {
  run(
    `npx prebuild-install --target=${PKG_NODE_TARGET} --arch=x64 --platform=win32`,
    bsq3Dir
  );

  // Embed the now-v108 binary as base64 before compiling, so the generated
  // module has real content when tsc/pkg process it.
  const base64 = fs.readFileSync(devBinary).toString('base64');
  fs.writeFileSync(
    generatedFile,
    `// Generated by scripts/package.js — see the comment in scripts/package.js\n// and sync/queue.ts's resolveNativeBinding for why this exists.\nexport const NATIVE_BINDING_BASE64 = '${base64}'\n`
  );

  run('npx tsc', root);
  run(
    'npx pkg dist/index.js --targets node18-win-x64 --output build/PitWallAgent.exe',
    root
  );
} finally {
  fs.copyFileSync(devBackup, devBinary);
  fs.unlinkSync(devBackup);
  fs.writeFileSync(generatedFile, PLACEHOLDER);
}
